path_to_driver = "C:\Program Files (x86)\chromedriver.exe"
login_url = "https://is.muni.cz/auth"
student_page = "https://is.muni.cz/auth/student/"
UCO = "fill me in"
primary_password = "fill me in"
